version: "3.9"

services:
  app:
    build:
      context: .
      target: app
    networks:
      - mynet
    ports:
      - 80:80
    depends_on:
      - cacheredis
    volumes:
      - ./:/app

  script:
    build:
      context: .
      target: updater
    command: python scripts/script.py
    networks:
      - mynet
    volumes:
      - ./:/app

  cacheredis:
    hostname: redis
    image: redis:latest
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
